repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: ^tests/.*\.data/
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/python-poetry/poetry
  rev: 2.0.1
  hooks:
  - id: poetry-check
  - id: poetry-lock
- repo: https://github.com/python-poetry/poetry
  rev: 2.0.1
  hooks:
  - id: poetry-install
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.4
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format
