# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/jitters.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/jitters.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16messages/jitters.proto\"[\n\x0fJitterTemplates\x12,\n\ttemplates\x18\x01 \x03(\x0b\x32\x19.JitterTemplates.Template\x1a\x1a\n\x08Template\x12\x0e\n\x06values\x18\x01 \x03(\x02'
)




_JITTERTEMPLATES_TEMPLATE = _descriptor.Descriptor(
  name='Template',
  full_name='JitterTemplates.Template',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='JitterTemplates.Template.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=117,
)

_JITTERTEMPLATES = _descriptor.Descriptor(
  name='JitterTemplates',
  full_name='JitterTemplates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='templates', full_name='JitterTemplates.templates', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JITTERTEMPLATES_TEMPLATE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=117,
)

_JITTERTEMPLATES_TEMPLATE.containing_type = _JITTERTEMPLATES
_JITTERTEMPLATES.fields_by_name['templates'].message_type = _JITTERTEMPLATES_TEMPLATE
DESCRIPTOR.message_types_by_name['JitterTemplates'] = _JITTERTEMPLATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JitterTemplates = _reflection.GeneratedProtocolMessageType('JitterTemplates', (_message.Message,), {

  'Template' : _reflection.GeneratedProtocolMessageType('Template', (_message.Message,), {
    'DESCRIPTOR' : _JITTERTEMPLATES_TEMPLATE,
    '__module__' : 'messages.jitters_pb2'
    # @@protoc_insertion_point(class_scope:JitterTemplates.Template)
    })
  ,
  'DESCRIPTOR' : _JITTERTEMPLATES,
  '__module__' : 'messages.jitters_pb2'
  # @@protoc_insertion_point(class_scope:JitterTemplates)
  })
_sym_db.RegisterMessage(JitterTemplates)
_sym_db.RegisterMessage(JitterTemplates.Template)


# @@protoc_insertion_point(module_scope)
