# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/librettos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from enumerations import phoneme_pb2 as enumerations_dot_phoneme__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/librettos.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18messages/librettos.proto\x1a\x1a\x65numerations/phoneme.proto\"\xd9\x01\n\x11RecordedLibrettos\x12\x36\n\tlibrettos\x18\x01 \x03(\x0b\x32#.RecordedLibrettos.RecordedLibretto\x1a:\n\x10RecordedLibretto\x12&\n\x05notes\x18\x01 \x03(\x0b\x32\x17.RecordedLibrettos.Note\x1aP\n\x04Note\x12\x16\n\x04name\x18\x01 \x02(\x0e\x32\x08.Phoneme\x12\x18\n\x10startTimeSeconds\x18\x02 \x02(\x02\x12\x16\n\x0e\x65ndTimeSeconds\x18\x03 \x02(\x02'
  ,
  dependencies=[enumerations_dot_phoneme__pb2.DESCRIPTOR,])




_RECORDEDLIBRETTOS_RECORDEDLIBRETTO = _descriptor.Descriptor(
  name='RecordedLibretto',
  full_name='RecordedLibrettos.RecordedLibretto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='RecordedLibrettos.RecordedLibretto.notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=192,
)

_RECORDEDLIBRETTOS_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='RecordedLibrettos.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RecordedLibrettos.Note.name', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTimeSeconds', full_name='RecordedLibrettos.Note.startTimeSeconds', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTimeSeconds', full_name='RecordedLibrettos.Note.endTimeSeconds', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=274,
)

_RECORDEDLIBRETTOS = _descriptor.Descriptor(
  name='RecordedLibrettos',
  full_name='RecordedLibrettos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='librettos', full_name='RecordedLibrettos.librettos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RECORDEDLIBRETTOS_RECORDEDLIBRETTO, _RECORDEDLIBRETTOS_NOTE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=274,
)

_RECORDEDLIBRETTOS_RECORDEDLIBRETTO.fields_by_name['notes'].message_type = _RECORDEDLIBRETTOS_NOTE
_RECORDEDLIBRETTOS_RECORDEDLIBRETTO.containing_type = _RECORDEDLIBRETTOS
_RECORDEDLIBRETTOS_NOTE.fields_by_name['name'].enum_type = enumerations_dot_phoneme__pb2._PHONEME
_RECORDEDLIBRETTOS_NOTE.containing_type = _RECORDEDLIBRETTOS
_RECORDEDLIBRETTOS.fields_by_name['librettos'].message_type = _RECORDEDLIBRETTOS_RECORDEDLIBRETTO
DESCRIPTOR.message_types_by_name['RecordedLibrettos'] = _RECORDEDLIBRETTOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordedLibrettos = _reflection.GeneratedProtocolMessageType('RecordedLibrettos', (_message.Message,), {

  'RecordedLibretto' : _reflection.GeneratedProtocolMessageType('RecordedLibretto', (_message.Message,), {
    'DESCRIPTOR' : _RECORDEDLIBRETTOS_RECORDEDLIBRETTO,
    '__module__' : 'messages.librettos_pb2'
    # @@protoc_insertion_point(class_scope:RecordedLibrettos.RecordedLibretto)
    })
  ,

  'Note' : _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
    'DESCRIPTOR' : _RECORDEDLIBRETTOS_NOTE,
    '__module__' : 'messages.librettos_pb2'
    # @@protoc_insertion_point(class_scope:RecordedLibrettos.Note)
    })
  ,
  'DESCRIPTOR' : _RECORDEDLIBRETTOS,
  '__module__' : 'messages.librettos_pb2'
  # @@protoc_insertion_point(class_scope:RecordedLibrettos)
  })
_sym_db.RegisterMessage(RecordedLibrettos)
_sym_db.RegisterMessage(RecordedLibrettos.RecordedLibretto)
_sym_db.RegisterMessage(RecordedLibrettos.Note)


# @@protoc_insertion_point(module_scope)
