# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/recording.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from enumerations import phoneme_pb2 as enumerations_dot_phoneme__pb2
from enumerations import theme_pb2 as enumerations_dot_theme__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages/recording.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18messages/recording.proto\x1a\x1a\x65numerations/phoneme.proto\x1a\x18\x65numerations/theme.proto\"\xf6\x03\n\x10RecordingMessage\x12\x15\n\x05theme\x18\x01 \x02(\x0e\x32\x06.Theme\x12%\n\x05parts\x18\x02 \x03(\x0b\x32\x16.RecordingMessage.Part\x1ai\n\x04Part\x12%\n\x05notes\x18\x01 \x03(\x0b\x32\x16.RecordingMessage.Note\x12:\n\x0bstartSuffix\x18\x02 \x03(\x0b\x32%.RecordingMessage.PhonemeWithDuration\x1az\n\x04Note\x12\x13\n\x0btimeSeconds\x18\x01 \x02(\x02\x12\x11\n\tmidiPitch\x18\x02 \x02(\x02\x12\x36\n\rlibrettoChunk\x18\x03 \x02(\x0b\x32\x1f.RecordingMessage.LibrettoChunk\x12\x12\n\ncontrolled\x18\x04 \x01(\x08\x1a|\n\rLibrettoChunk\x12\x34\n\x05vowel\x18\x01 \x02(\x0b\x32%.RecordingMessage.PhonemeWithDuration\x12\x35\n\x06suffix\x18\x02 \x03(\x0b\x32%.RecordingMessage.PhonemeWithDuration\x1a?\n\x13PhonemeWithDuration\x12\x16\n\x04name\x18\x01 \x02(\x0e\x32\x08.Phoneme\x12\x10\n\x08\x64uration\x18\x02 \x02(\x02'
  ,
  dependencies=[enumerations_dot_phoneme__pb2.DESCRIPTOR,enumerations_dot_theme__pb2.DESCRIPTOR,])




_RECORDINGMESSAGE_PART = _descriptor.Descriptor(
  name='Part',
  full_name='RecordingMessage.Part',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='notes', full_name='RecordingMessage.Part.notes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startSuffix', full_name='RecordingMessage.Part.startSuffix', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=270,
)

_RECORDINGMESSAGE_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='RecordingMessage.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeSeconds', full_name='RecordingMessage.Note.timeSeconds', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='midiPitch', full_name='RecordingMessage.Note.midiPitch', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='librettoChunk', full_name='RecordingMessage.Note.librettoChunk', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='controlled', full_name='RecordingMessage.Note.controlled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=394,
)

_RECORDINGMESSAGE_LIBRETTOCHUNK = _descriptor.Descriptor(
  name='LibrettoChunk',
  full_name='RecordingMessage.LibrettoChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vowel', full_name='RecordingMessage.LibrettoChunk.vowel', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='suffix', full_name='RecordingMessage.LibrettoChunk.suffix', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=520,
)

_RECORDINGMESSAGE_PHONEMEWITHDURATION = _descriptor.Descriptor(
  name='PhonemeWithDuration',
  full_name='RecordingMessage.PhonemeWithDuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RecordingMessage.PhonemeWithDuration.name', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration', full_name='RecordingMessage.PhonemeWithDuration.duration', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=522,
  serialized_end=585,
)

_RECORDINGMESSAGE = _descriptor.Descriptor(
  name='RecordingMessage',
  full_name='RecordingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='theme', full_name='RecordingMessage.theme', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parts', full_name='RecordingMessage.parts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RECORDINGMESSAGE_PART, _RECORDINGMESSAGE_NOTE, _RECORDINGMESSAGE_LIBRETTOCHUNK, _RECORDINGMESSAGE_PHONEMEWITHDURATION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=585,
)

_RECORDINGMESSAGE_PART.fields_by_name['notes'].message_type = _RECORDINGMESSAGE_NOTE
_RECORDINGMESSAGE_PART.fields_by_name['startSuffix'].message_type = _RECORDINGMESSAGE_PHONEMEWITHDURATION
_RECORDINGMESSAGE_PART.containing_type = _RECORDINGMESSAGE
_RECORDINGMESSAGE_NOTE.fields_by_name['librettoChunk'].message_type = _RECORDINGMESSAGE_LIBRETTOCHUNK
_RECORDINGMESSAGE_NOTE.containing_type = _RECORDINGMESSAGE
_RECORDINGMESSAGE_LIBRETTOCHUNK.fields_by_name['vowel'].message_type = _RECORDINGMESSAGE_PHONEMEWITHDURATION
_RECORDINGMESSAGE_LIBRETTOCHUNK.fields_by_name['suffix'].message_type = _RECORDINGMESSAGE_PHONEMEWITHDURATION
_RECORDINGMESSAGE_LIBRETTOCHUNK.containing_type = _RECORDINGMESSAGE
_RECORDINGMESSAGE_PHONEMEWITHDURATION.fields_by_name['name'].enum_type = enumerations_dot_phoneme__pb2._PHONEME
_RECORDINGMESSAGE_PHONEMEWITHDURATION.containing_type = _RECORDINGMESSAGE
_RECORDINGMESSAGE.fields_by_name['theme'].enum_type = enumerations_dot_theme__pb2._THEME
_RECORDINGMESSAGE.fields_by_name['parts'].message_type = _RECORDINGMESSAGE_PART
DESCRIPTOR.message_types_by_name['RecordingMessage'] = _RECORDINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecordingMessage = _reflection.GeneratedProtocolMessageType('RecordingMessage', (_message.Message,), {

  'Part' : _reflection.GeneratedProtocolMessageType('Part', (_message.Message,), {
    'DESCRIPTOR' : _RECORDINGMESSAGE_PART,
    '__module__' : 'messages.recording_pb2'
    # @@protoc_insertion_point(class_scope:RecordingMessage.Part)
    })
  ,

  'Note' : _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), {
    'DESCRIPTOR' : _RECORDINGMESSAGE_NOTE,
    '__module__' : 'messages.recording_pb2'
    # @@protoc_insertion_point(class_scope:RecordingMessage.Note)
    })
  ,

  'LibrettoChunk' : _reflection.GeneratedProtocolMessageType('LibrettoChunk', (_message.Message,), {
    'DESCRIPTOR' : _RECORDINGMESSAGE_LIBRETTOCHUNK,
    '__module__' : 'messages.recording_pb2'
    # @@protoc_insertion_point(class_scope:RecordingMessage.LibrettoChunk)
    })
  ,

  'PhonemeWithDuration' : _reflection.GeneratedProtocolMessageType('PhonemeWithDuration', (_message.Message,), {
    'DESCRIPTOR' : _RECORDINGMESSAGE_PHONEMEWITHDURATION,
    '__module__' : 'messages.recording_pb2'
    # @@protoc_insertion_point(class_scope:RecordingMessage.PhonemeWithDuration)
    })
  ,
  'DESCRIPTOR' : _RECORDINGMESSAGE,
  '__module__' : 'messages.recording_pb2'
  # @@protoc_insertion_point(class_scope:RecordingMessage)
  })
_sym_db.RegisterMessage(RecordingMessage)
_sym_db.RegisterMessage(RecordingMessage.Part)
_sym_db.RegisterMessage(RecordingMessage.Note)
_sym_db.RegisterMessage(RecordingMessage.LibrettoChunk)
_sym_db.RegisterMessage(RecordingMessage.PhonemeWithDuration)


# @@protoc_insertion_point(module_scope)
