name: release
on:
  release:
    types: [created]
  push:
jobs:
  release:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pipx install poetry
    - uses: actions/setup-python@v5
      with:
        cache: poetry
        python-version: '3.10'
    - run: poetry install
    - uses: tschm/token-mint-action@v1.0.3
      id: mint
    - run: poetry publish --build -u __token__ -p $PYPI_TOKEN
      env:
        PYPI_TOKEN: ${{ steps.mint.outputs.api-token }}
      if: false
    - run: poetry run poe document
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./documentation/module/_build/html
  deploy-pages:
    needs: release
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
