name: test
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action:
        - test
        - coverage
    steps:
    - run: pipx install poetry
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: poetry
        python-version: '3.10'
    - run: poetry install
    - run: poetry run poe ${{ matrix.action }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: poetry-lock
